### ISSUE TITLE
WinNT executable (MinGW) ?

### ISSUE THREAD

**Issue by blackcrack** [stachenov/quazip#10]
Hi,

this is interesting, can you upload an executable for WinNT in our releases ?
can be maybe a interesting thing for reactos.org ? 
The zipfolder be already implement, like i become with, 
but as cmd option maybe also interesting ..
is there maby a possible to implement a possible for creating iso's,
something maybe also packing in .. quazip -iso [folder] or quazip -x folder.iso ./tofolder

just as idea .. maybe more options in a single exe more better as only one purpose ;)

best regards
Blacky

**Comment by stachenov** [comment]
QuaZIP is a library, not an application. It can't be executable.
