### ISSUE TITLE
quazip unzip issue

### ISSUE THREAD

**Issue by mansouriHassan** [stachenov/quazip#106]
Hi

i use quazip with qt c++, i use JlCompresse::extractDir() function to extract zip file, my app display this issue : 
"QuaZip::goToFirstFile(): ZIP is not open in mdUnzip mode"

**Comment by stachenov** [comment]
The path to the input file is probably incorrect or the file is not accessible for reading.

**Comment by mansouriHassan** [comment]
thanks for your response

I make sure that the path to the input file is correct and the file is
accessible for reading

Le jeu. 7 janv. 2021 à 16:04, Sergei Tachenov <notifications@github.com> a
écrit :

**Comment by mansouriHassan** [comment]
I make sure that the path to the input file is correct and the file is accessible for reading

**Comment by mansouriHassan** [comment]
this function "**unzOpenInternal(ioDevice, NULL, 1, flags)**" in quazip.cpp file **return null**

**Comment by stachenov** [comment]
Another possibility is that the input file is corrupt.

To make sure, make an MCVE. A shortest code possible to reproduce the problem, with a sample input file attached.

**Comment by mansouriHassan** [comment]
i test with a small file its OK, is the problem that file size is huge (size = 177 MB) ?

**Comment by stachenov** [comment]
This size shouldn't be a problem... But it could be corrupt or perhaps it uses some non-standard extensions to the ZIP format not supported by QuaZip. Need to see the file to tell exactly.

**Comment by mansouriHassan** [comment]
i verify my file, its a non-standard extensions to the ZIP format, thanks
