### ISSUE TITLE
Quazipfile returns error -3 when reading a password-protected archive

### ISSUE THREAD

**Issue by perseedossrajiv** [stachenov/quazip#112]
I've got some password protected zip files that I was opening using Quazip, I'd simply do:
QuaZipFile InFile(&ZipArchive);
for (bool NextExist = ZipArchive.goToFirstFile(); NextExist; NextExist = ZipArchive.goToNextFile())
{
    InFile.open(QIODevice::ReadOnly, Password);
    ...

This worked when i was using Qt 5.6.1. I've recently switched to Qt 5.12.1 and it's not working anymore. InFile.readAll() gives me an error -3.

Can you please help? Thanks

**Comment by stachenov** [comment]
Well, obviously I need a sample file and a short, self-contained, compilable code sample.

**Comment by perseedossrajiv** [comment]
Ok, I've investigated where things stopped working as i moved quazip branches from 0.2.3 upwards and this is the commit that caused the issue:
Type of pcrc_32_tab (bug #44) (git commit : 5f48264e078c1cc5f0682e90acc9ef0c8f011c19)

I'm using zlib 1.2.5. Switching to zlib 1.2.11 fixes the issue.

Thanks

**Comment by Neustradamus** [comment]
@perseedossrajiv: There is a Zlib 1.3.1 with 2 CVE fixes for minizip.
