### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by NomisEgnal** [stachenov/quazip#118]
hi,

I have two zip-files. If I generate QuaZipFileInfo of these two files  (by QuaZip 1.0) it is different. 
1.zip makes the expected result. 2.zip generates one FileInfo more, because it produces also a "measure/" file. But this is a subdirectory inside the zip-File. 

Any idea ?

Thanks and regards
Simon

[1.zip](https://github.com/stachenov/quazip/files/6516814/1.zip)
[2.zip](https://github.com/stachenov/quazip/files/6516815/2.zip)

**Comment by stachenov** [comment]
Subdirectories sometimes have separate entries for them. It is useful when you need to store some of their attributes, such as Unix permissions or ownership info. They are also required if you want to have an empty directory in the archive. They are distinguished by the trailing slash. But they aren't always required, as if a directory is missing, it will be created automatically when unpacking, if there are files with paths starting with that directory.
