### ISSUE TITLE
Creating Password protected ZIP

### ISSUE THREAD

**Issue by ahsnuet** [stachenov/quazip#122]
Greetings,

Does **quazip** allows to create password protected ZIP file.

Best regards,
Ahsan

**Comment by stachenov** [comment]
It does, but with several limitations: first, only the most basic encryption is supported (traditional PKWARE encryption), and this feature is not available through the `JlCompress` utility class, meaning you'll have to use the lower level API of `QuaZip/QuaZipFile`, which isn't very convenient.
