### ISSUE TITLE
JlCompress miss hidden files.

### ISSUE THREAD

**Issue by detorto** [stachenov/quazip#124]
Compressing directory using  JlCompress::compressDir on linux creates arhive missing all ".*" files. 
Probably have to add QDir::Hidden flag to JlCompress::compressSubDir.

**Comment by stachenov** [comment]
That's right, it doesn't compress hidden files, just like [the docs](https://stachenov.github.io/quazip/classJlCompress.html#a8708eafcadc5c192a1d492e784cfc98f) say. Whether it's a good or a bad API design decision is debatable (although I tend to think it's a bad one), but thankfully, there's this `compressDir()` overload accepting a `filters` argument that can be used to pass `QDir::Hidden`.

Making it a default would break the API, possibly leading to unpleasant surprises to some users, and that's not a good thing. Maybe in QuaZip 2.0 (100 years later or something).
