### ISSUE TITLE
The binary file is not generated 

### ISSUE THREAD

**Issue by Yisus7u7** [stachenov/quazip#126]
Hello, compile quazip on Android [(Termux) ](https://www.termux.org) And the executable file is not generated, why? 
![Screenshot_20210804-124352](https://user-images.githubusercontent.com/64093255/128229221-8e248d84-3951-46e4-9f20-007d91a48293.png)
![Screenshot_20210804-124327](https://user-images.githubusercontent.com/64093255/128229234-2c75a409-e9b1-4aa1-bce5-003b4325facd.png)

**Comment by jonaski** [comment]
What executable file?

**Comment by Yisus7u7** [comment]
I mean, the executable file, `quazip` , that file is not generated

**Comment by Yisus7u7** [comment]
I ran make install and everything if it worked, but the executable file that goes in the /bin folder did not appear

**Comment by jonaski** [comment]
The only executable there is qztest, which is the unit test. You need to have Qt test installed to build the unit tests.

**Comment by Yisus7u7** [comment]
So what are the build instructions?

**Comment by Yisus7u7** [comment]
I think I'm confused, is quazip an application or is it a library?

**Comment by stachenov** [comment]
It is a C++ library for developing applications with Qt (a toolkit consisting of libraries and various utilities used by software developers). If you're not a developer, you probably have no need of it, unless if you're trying to compile an application that depends on QuaZip.

**Comment by Yisus7u7** [comment]
Oh ok, now I understand everything, I thought quazip was an app, sorry for the hassle

**Comment by Yisus7u7** [comment]
Can you tell me any application that uses the quazip library?

**Comment by Yisus7u7** [comment]
I explain, I'm just looking for apps and libraries to add to the graphical environment of the termux application

**Comment by stachenov** [comment]
No, not really. I initially developed this library to use at work for some in-house software. This is actually the second time I hear it can be compiled for Android at all!

Although I'm not really aware of any non-android apps that use it either... Sure thing, some app developers create issues, and some mention apps they develop, but I don't seem to remember any of those.

**Comment by Yisus7u7** [comment]
![Screenshot_20210802-163457](https://user-images.githubusercontent.com/64093255/128242518-4d4f8ec5-9283-4a9c-b8ee-ec341b65aa73.png)

When I say Android, I mean Termux, termux is a terminal emulator with package manager for Android, does not require root and runs a Linux environment on the cell phone, termux does not use root (sudo) and has more than 1000 packages, termux natively uses Android APIs, but the apps and libraries compiled on it are still similar to those of a Unix system

**Comment by Yisus7u7** [comment]
And termux provides a graphical environment, it can be manipulated using wayland and vnc, that screenshot I mentioned are screenshots of my cell phone, it's a normal android cell phone with termux and xfce4

**Comment by Yisus7u7** [comment]
So when I say "some app that uses the quazip library", I mean an app for linux, to compile the en termux

**Comment by stachenov** [comment]
Yeah, I know what Termux is. Use it myself.

No, I don't know any Linux apps either, as I've already mentioned.

**Comment by Yisus7u7** [comment]
If you do not know what termux is, here is the information :  
https://wiki.termux.com/wiki/FAQ

**Comment by Yisus7u7** [comment]
> Yeah, I know what Termux is. Use it myself.
> 
> No, I don't know any Linux apps either, as I've already mentioned.

Oh ok, I'll find out on my own, same thanks, maybe soon add this library
