### ISSUE TITLE
Error compiling quazip

### ISSUE THREAD

**Issue by lincolningaroca** [stachenov/quazip#128]
Hi guys, I have the following error when trying to compile quazip in the terminal, I already have the zlib library compiled in a zlib folder, in the root of the project, but it still does not compile quazip, any suggestion would be appreciated.

![image](https://user-images.githubusercontent.com/13387428/131070234-a8a725d3-5b0c-4a49-96f3-b06d2474203d.png)

**Comment by stachenov** [comment]
Just found some time to take a look at it.

It looks to me like you're trying to use quazip/CMakeLists.txt directly. It isn't supposed to be used like this. It's the root CMakeLists.txt that must be used.

However, if that's the case, then it should've errored out earlier, when it didn't encounter `cmake_minimum_required` and other mandatory stuff. So I'm not sure it's the case.

Either way, the reason seems to be that some variables, like `QUAZIP_LIB_TARGET_NAME` are missing. That, coupled with the `quazip-1.1/quazip` part of your command line, lead me to thinking that using the wrong CMakeLists.txt could be the cause.

**Comment by lincolningaroca** [comment]
![image](https://user-images.githubusercontent.com/13387428/131563274-5e41dd1d-0373-4e81-84bd-aa942b7238f8.png)
Thanks for your answer, now I get this error, it finds zlib but not the headers, that's what I think is happening.

**Comment by stachenov** [comment]
The only thing clear is that the linker is missing some symbols. The two most likely reasons are that either some library is missing, or the library that was used to compile (the headers) is different from the binary. There's definitely something wrong with your setup, but I can't tell what it is.

Can you create a simple CMake project that uses your zlib and try to compile it? Then we can at least figure out whether it's a QuaZip problem at all.

**Comment by lincolningaroca** [comment]
Ok thanks, I will try to compile it in another way.

**Comment by lincolningaroca** [comment]
Hello again, after having tried to compile the new version 1.2, as I keep getting the same errors that I previously reported, and well the truth is that I no longer know what to do, I would appreciate any help.
![image](https://user-images.githubusercontent.com/13387428/148632553-d207b56f-0bfc-499c-92cb-4b2b5c232142.png)
![image](https://user-images.githubusercontent.com/13387428/148632566-d93bc4e8-9170-46e1-a1ef-9533ef94f5b7.png)
![image](https://user-images.githubusercontent.com/13387428/148632574-9b78c296-57d3-4a10-a945-d0dd12645fff.png)

**Comment by stachenov** [comment]
You're trying to link an MSVC build of ZLIB with a MinGW build of Qt. These builds are totally binary incompatible. It's never going to work, like it wouldn't work to link a Linux app to a DLL copied from a Windows PC.

Either get a MinGW ZLIB build to link to, or set the CMake option `QUAZIP_USE_QT_ZLIB` to make QuaZip use ZLIB bundled with Qt (OFF by default).

**Comment by lincolningaroca** [comment]
Ok thank you very much, so I am and if you can generate the library, thank you again for your answer, greetings.

![image](https://user-images.githubusercontent.com/13387428/148653029-5c04a76f-e334-4617-bcf0-f457b70aea81.png)
![image](https://user-images.githubusercontent.com/13387428/148653042-9145dd01-21f8-4fd8-87b6-0acff976e1bb.png)
