### ISSUE TITLE
Qt Application: ZIP is not open in mdUnzip mode

### ISSUE THREAD

**Issue by lvoid** [stachenov/quazip#129]
- **Operating System**: Ubuntu 20.04.3
- **Qt**: 5.12.8
- **QuaZip**: v.1.1
- **zlib** v.1.2.11
- **CMake**: v.3.21.2

I have built zlib and imported it as a 3rd party library in Qt creator.

I also built QuaZip with CMake as indicated in the documentation, and imported it as a 3rd party library in Qt creator.  Dynamically linked.  My .pro file looks like this now:

```
unix:!macx: LIBS += -L$$PWD/../../../usr/local/lib/ -lquazip1-qt5

INCLUDEPATH += $$PWD/../../../usr/local/include/QuaZip-Qt5-1.1
DEPENDPATH += $$PWD/../../../usr/local/include/QuaZip-Qt5-1.1

unix:!macx: LIBS += -L$$PWD/../../../usr/local/zlib/lib/ -lz

INCLUDEPATH += $$PWD/../../../usr/local/zlib/include
DEPENDPATH += $$PWD/../../../usr/local/zlib/include
```

I am able to successfuly import QuaZip into my header files in my project.  I have a function that is unzipping a .zip file as follows (I've checked that the path is indeed correct):

```c++
bool Reader::loadCbzFile(QString cbzFile)
{
    qDebug() << cbzFile;

    QuaZip zip(cbzFile);
    if (!zip.open(QuaZip::mdUnzip))
            qDebug() << "error";

    const QStringList fileList = zip.getFileNameList();
    QStringList allFiles = JlCompress::extractFiles(cbzFile, fileList);

    QImage newImage;
    for(int file = 0; file < fileList.size(); file++) {
        QImageReader reader(allFiles[file]);
        newImage = reader.read();

        if(newImage.isNull()) return false;

        m_mangaImages.push_back(newImage); //save image to class variable
    }

    qDebug() << m_mangaImages.size();
    return true;
}
```

Whenever I try to do this, I get an "error" printed out along with 

`QuaZip::getFileNameList/getFileInfoList(): ZIP is not open in mdUnzip mode`

It does not successfully unzip the file.  Any idea what's going on?

**Comment by stachenov** [comment]
That's... strange.

One thing that's wrong with your code is that you're opening the file with `zip.open()` and then use `JlCompress` anyway. You could just use `JlClompress::extractDir` instead, which would simply unpack the archive in the directory provided.

What you're trying to do instead is to open the same file _twice:_ once directly, once indirectly via `JlCompress`. That shouldn't cause any errors, though, unless your OS just doesn't let you open the same file twice, but that's unlikely, given it's read access, not write.

Could you try this in a debugging session to figure out what line of code prints that message. I suspect it's `zip.getFileNameList()`, but I'd like to make sure.

**Comment by lvoid** [comment]
Sergei,

You're correct.  The line that prints the code is `zip.getFileNameList()`,

However, this is my mistake.  It turns out that the Qt file selector was NOT putting in the correct absolute path - the path was missing the initial `/` in front of `/home/`, so it resulted in that `ZIP is not open in mdUnzip mode` error being thrown for some reason.  I didn't know what to make of it.

Using `QStringList allFiles = JlCompress::extractDir("/path/to/zip")` works perfectly and extract the files.
