### ISSUE TITLE
Building on Windows with Cmake and looking at Conan

### ISSUE THREAD

**Issue by ShamanTcler** [stachenov/quazip#13]
I am about to try to update your CMakeLists.txt file to use Conan ( a C++ package manager www.conan.io )

But before I get started, is zlib/1.2.11 adequate?

Looking to build for MSVS 2015, Qt 5.9,X and 5.12, and maybe MSVS 2012.

If you are interested in my final CMakeLists.txt  it is yours.

**Comment by stachenov** [comment]
CMakeLists.txt was contributed by someone, I don't even use it. So I don't know whether it's a good idea or not.

I have never ever had any problems with any zlib versions.

**Comment by dbrgn** [comment]
This can probably be closed, now that Cmake is offically supported?
