### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by lanmanck** [stachenov/quazip#139]
Hi guys.
here is my error , I follow this but has error: https://stachenov.github.io/quazip/:

![微信截图_20211209092137](https://user-images.githubusercontent.com/3500166/145317126-d222c6a5-97a4-4c09-8676-7563cc91e004.png)

I suggest add a how-to-build.MD file to the project and show us how to build ,step by step, I am new to cmake. 
Thanks.

**Comment by lanmanck** [comment]
After locate to parent folder, it shows another error.

`
CMake Error at CMakeLists.txt:59 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
`
I found Qt5Config.cmake is located in : c:\Qt\Qt5.14.1\5.14.1\msvc2017_64\lib\cmake\Qt5\? but how to set CMAKE_PREFIX_PATH ?
![微信截图_20211209093405](https://user-images.githubusercontent.com/3500166/145318314-5128df44-f4b9-4f34-b0d0-79a731b1c4f6.png)

**Comment by stachenov** [comment]
Try running `c:\Qt\Qt5.14.1\5.14.1\msvc2017_64\bin\qtenv2.bat` or something like that. CMake should be able to find Qt if it's set up properly and in the PATH, no additional setup needed.

**Comment by tHeBeStXu** [comment]
@lanmanck Hi, You can use CMake(cmake-gui). 
![image](https://user-images.githubusercontent.com/12775278/167244653-2629d59a-4324-4873-88b9-95136cf4153e.png)
Set the cmake settings as following pic.
![image](https://user-images.githubusercontent.com/12775278/167244914-66fb5fa5-28b9-4b61-a175-fe5e90358afe.png)
After you click generate, it will shows up a **QuaZip.sln** file in your folder.
Next, open the **QuaZip.sln** by your IDE(MSVC 2015 x64 in my case) and **Build Solution** , and finally, right click the **INSTALL** in the Solution Explorer and select **Project Only** -> **Build Only INSTALL**, it will generate all the files you need for your own projects.

**Comment by cen1** [comment]
The main readme has been expanded with all kinds of build variations and how to locate Qt installs.
