### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [stachenov/quazip#140]
Dear @stachenov,

In first, I wish you a Happy New Year.

It will be nice to remove old parts like:
- https://sourceforge.net/p/quazip/wiki/Home/
- https://sourceforge.net/p/quazip/_list/tickets
- https://sourceforge.net/p/quazip/bugs/
- https://sourceforge.net/p/quazip/support-requests/
- https://sourceforge.net/p/quazip/patches/
- https://sourceforge.net/p/quazip/feature-requests/
- https://sourceforge.net/p/quazip/code/HEAD/tree/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/quazip/

To disable/delete tabs, go here: https://sourceforge.net/projects/quazip/
To add a new tab, go here: https://sourceforge.net/projects/quazip/
To change informations, go here: https://sourceforge.net/p/quazip/admin/overview
To export, go here: https://sourceforge.net/p/quazip/admin/export

The new place "https://github.com/stachenov/quazip" can be added in:
- "Moved Project to", here: https://sourceforge.net/p/quazip/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/quazip/admin/overview
- A new tab, go here: https://sourceforge.net/projects/quazip/

Thanks in advance.

**Comment by stachenov** [comment]
Good idea, I'll get to it as soon as I can, and as soon as I manage to find/restore my SF credentials. It's been a long time since I've even visited the site...

**Comment by stachenov** [comment]
Done. Some tabs couldn't be removed, and I've decided to leave the tickets alone (some commits refer to them), just revoked permissions to create new tickets.

**Comment by Neustradamus** [comment]
@stachenov: Thanks :)

About tickets tabs, you can export in a backup and import, if you want.

To remove:
- https://i.ibb.co/3r05P3H/sourceforge-gear-tickets.png

**Comment by stachenov** [comment]
I'm not sure that backup/import would preserve ticket numbers, so I'll just leave them as they are.
