### ISSUE TITLE
Current release doesn't include the latest patch

### ISSUE THREAD

**Issue by flowln** [stachenov/quazip#144]
The [last PR](https://github.com/stachenov/quazip/pull/141) was merged quite a while ago. It makes changes that are required by some applications (as explained in the PR). The problem is that packages in Linux distributions generally use official releases to distribute Quazip, so using that patch requires either building from source from the last commit, or patching the package ourselves. This is true for the Gentoo package, and possibly others as well.

My request is that a minor version bump is done, so that package managers can use the newer version with that patch applied more easily.

**Comment by stachenov** [comment]
Makes sense. Will get to it as soon as I can, most probably within a few days.

**Comment by stachenov** [comment]
v1.3 is out.

**Comment by flowln** [comment]
Thank you! :D
