### ISSUE TITLE
Issue with conan and Qt 6

### ISSUE THREAD

**Issue by MartinDelille** [stachenov/quazip#145]
Hi,

I'm having an issue building quazip 1.3 with Qt 6:

```
CMake Error at source_subfolder/CMakeLists.txt:59 (find_package):
By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Qt5", but
CMake did not find one.

Could not find a package configuration file provided by "Qt5" with any of
the following names:

  Qt5Config.cmake
  qt5-config.cmake

Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
to a directory containing one of the above files.  If "Qt5" provides a
separate development package or SDK, be sure it has been installed.
```

I originally posted this issue here since I use quazip with conan: https://github.com/conan-io/conan-center-index/issues/10640

**Comment by stachenov** [comment]
This simply means that you either don’t have Qt 5 installed or CMake can’t find it due to some configuration / environment issues.

**Comment by stachenov** [comment]
Oops, missed the Qt 6 part. Yes, @jonaski is correct.

**Comment by MartinDelille** [comment]
Thanks! I indeed made a first try in this direction and my PR should fix quazip conan recipe! Thanks!

**Comment by MartinDelille** [comment]
I fixed the recipe thanks to your advice but still have an issue building quazip:

```
/Users/martin/.conan/data/qt/6.3.1/_/_/package/68d290489ff0abbdbed0bbf82d3be140fc585bbb/include/QtCore/qglobal.h:143:6: error: "Qt requires a C++17 compiler"
#    error "Qt requires a C++17 compiler"
     ^
In file included from /Users/martin/.conan/data/quazip/1.3/_/_/build/f830165d2a9df4c8df15a40a222715b4a39f6c7f/source_subfolder/quazip/quaadler32.cpp:26:
```

Any clue to fix this issue ?

**Comment by jonaski** [comment]
Use a newer compiler, Qt 6 require C++17.

**Comment by MartinDelille** [comment]
I'm using apple-clang which support C++ 17.

**Comment by stachenov** [comment]
Try to replace
```
set(CMAKE_CXX_STANDARD 14)
```
in QuaZip’s `CMakeLists.txt`
with
```
set(CMAKE_CXX_STANDARD 17)
```
If this works, I can try to make it conditional, to enable it only for Qt 6.

**Comment by stachenov** [comment]
I’m trying to implement automatic setting of the C++ standard, but it seems that it doesn’t work if I set it too late, after the Qt version is detected. The current implementation in the cpp17 branch doesn’t even work with Qt 5, it breaks with the message that C++11 is required. Will look into it further when I have time.

**Comment by stachenov** [comment]
Well, it turned out there was something wrong with my environment, as even when I switched back to master it would still fail to compile. Apparently I had a wrong version of Qt selected. After fixing it, it works fine now, at least with Qt 5, so I assume it should work fine with Qt 6 now too.

The changes are already in the master.

**Comment by MartinDelille** [comment]
Ok thanks!

I used your patch here: https://github.com/conan-io/conan-center-index/pull/11499
