### ISSUE TITLE
Can't build with QUAZIP_USE_QT_ZLIB on qt6 on windows

### ISSUE THREAD

**Issue by xlazom00** [stachenov/quazip#146]
Can't build with QUAZIP_USE_QT_ZLIB on qt6 on windows

cmake log
```
-- Could NOT find Qt6Zlib (missing: Qt6Zlib_DIR)
CMake Warning at C:/_WORK/lib_qt6_3_1_x64/qt5/qtbase/lib/cmake/Qt6/Qt6Config.cmake:263 (message):
  Failed to find Qt component "Zlib".

  Expected Config file at
  "C:/_WORK/lib_qt6_3_1_x64/qt5/qtbase/lib/cmake/Qt6Zlib/Qt6ZlibConfig.cmake"
  does NOT exist

Call Stack (most recent call first):
  CMakeLists.txt:78 (find_package)
```
They moved cmake to Qt6ZlibPrivate

And I also raised this bug https://bugreports.qt.io/browse/QTBUG-104475

**Comment by stachenov** [comment]
Well, apparently there’s nothing I can do about it since Qt 6 seems to consider Zlib a private implementation detail not to be used externally.

**Comment by xlazom00** [comment]
@stachenov private from Qt perspective mean that you can use that but API isn't stable and they don't guarantee anything. But I Think you can still use that and I think quazip can support that without any problem

**Comment by cen1** [comment]
Technically, if the library is still there in one form or the other, CMake could find it, in worst case with a custom Find.cmake script. However, if upstream stays as is, the more pragmatic decision is to simply disable this flag for Qt6. Especially with tools like conan, installing your own zlib is not a big deal.
