### ISSUE TITLE
 error: LNK2019: unresolved external symbol "__declspec(dllimport) public: static class QStringList __cdecl JlCompress::extractDir(class QString,class QString)" (__imp_?extractDir@JlCompress@@SA?AVQStrin

### ISSUE THREAD

**Issue by TodoRightNow** [stachenov/quazip#152]
I have compiled both qt and quazip into static libraries，But when I linked the quazip static library in my project, that reported such an unresolved external symbol, can someone help me, thanks!

**Comment by stachenov** [comment]
Sorry I'm like 2 months late, these were busy 2 months.

In case it's still relevant, it looks like you didn't actually link to the library. I need to see the full build log. Also knowing the OS and the compiler version would be helpful.

**Comment by TodoRightNow** [comment]
@stachenov First of all, thank you very much for your reply. I have solved this problem because I did not define the corresponding static macro in my project after compiling  this project into a static library
