### ISSUE TITLE
UTF-8 is not properly supported, even if choosen as file name encoding

### ISSUE THREAD

**Issue by denis-gz** [stachenov/quazip#16]
Currently, there is no proper support in QuaZIP for UTF-8 encoding in file names and comments in ZIP archive. On Windows, file names and comments (text-names hereon) are encoded in local OEM encoding, which easily leads to information loss. At the same time, changes in ZIP file format enabling the use of UTF-8 encoding were implemented back in 2006, and according to my tests, are supported by standard tools both on Windows (starting from Windows 7 SP1) and MacOS (at least on El Capitan 10.11). ZIP file format is documented here: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT. Proposed fix to this issue changes QuaZIP library in a way that it always creates archives with text-names encoded in UTF-8, and decodes text from UTF-8 if corresponding flag is detected in ZIP header. If no UTF-8 flag is detected, the behavior is unchanged (converting to Unicode using QTextCodec from current locale).

See pull request https://github.com/stachenov/quazip/pull/17.

**Comment by Tymolc** [comment]
Can this issue be closed, as PR #17 ist merged? 🙂

**Comment by denis-gz** [comment]
Yes, I suppose.
