### ISSUE TITLE
Change "Host OS" from Unix to FAT

### ISSUE THREAD

**Issue by florianstefanwerner** [stachenov/quazip#160]
Hi.
Is it possible to change the used "Host OS" from Unix to FAT, if I compress a file or directory? We would need this to be compatible to another part of our code.

![Host OS - Unix to Fat](https://user-images.githubusercontent.com/117750869/200598571-e04f9753-c932-4883-a33f-918fe0964c6d.png)

Kind regards

**Comment by florianstefanwerner** [comment]
Sorry, I am not so familiar with working with archives. Is there an option or a flag I can change, or what do I have to do to archieve this?

**Comment by stachenov** [comment]
Should be easy, but the earliest I can possibly get to this is the weekend because I've got a job to do on weekdays.

**Comment by florianstefanwerner** [comment]
If you can have a look at the weekend, this would be great! Thanks

**Comment by stachenov** [comment]
Finally had some free time for this.

See the `QuaZip::setDefaultOsCode()` and `QuaZip::setOsCode()` methods (static/global and per-instance respectively).

The codes themselves are described in the famous APPNOTE.txt as
```
        4.4.2.2 The current mappings are:

         0 - MS-DOS and OS/2 (FAT / VFAT / FAT32 file systems)
         1 - Amiga                     2 - OpenVMS
         3 - UNIX                      4 - VM/CMS
         5 - Atari ST                  6 - OS/2 H.P.F.S.
         7 - Macintosh                 8 - Z-System
         9 - CP/M                     10 - Windows NTFS
        11 - MVS (OS/390 - Z/OS)      12 - VSE
        13 - Acorn Risc               14 - VFAT
        15 - alternate MVS            16 - BeOS
        17 - Tandem                   18 - OS/400
        19 - OS X (Darwin)            20 thru 255 - unused
```

Whatever your software means by FAT, I'm unsure, but most likely it's zero.

Please either close this issue if it's what you were looking for, or comment otherwise.

**Comment by florianstefanwerner** [comment]
Yes, this was what I am looking for. Thank you very much!
