### ISSUE TITLE
Unable to open a zip file in the application resources on Windows

### ISSUE THREAD

**Issue by MartinDelille** [stachenov/quazip#167]
I have an issue when trying to open a zip file contained the application resource (via the qrc file).

It works fine on MacOS.

**Comment by cen1** [comment]
If this is still relevant please reopen with some more info and possibly a code snippet.

One would assume you are trying to extract` QFile inputFile(":\\data\\archive.zip");` straight away without first copying the data file to a location on disk. It should work in theory but I imagine there could be some issue the way qrc works. The one issue I remember on Windows was that all qrc files ended up as read-only files when moved to disk, but I am not sure if this would cause issues with unzipping.
