### ISSUE TITLE
Install instruction from documentation fails (Unknown argument -D) (Linux)

### ISSUE THREAD

**Issue by domichbt** [stachenov/quazip#178]
When following the building and installation instructions from the documentation, 

```cmake --build wherever/you/want/your/build/to/be --target install -D CMAKE_INSTALL_PREFIX=/wherever/you/want/to/install```

returns ```Unknown argument -D``` .

This is on linux (Pop!_OS 22.04 so essentially Ubuntu 22.04), using cmake 3.22.1

**Comment by cen1** [comment]
That should be set at configure step, I removed the offending flag from the doc. FIxed in https://github.com/stachenov/quazip/commit/3d05f42bf0e369361bfece4e11027d3181de5495
