### ISSUE TITLE
CMake errors when configuring from latest QuaZip (1.4)

### ISSUE THREAD

**Issue by bobhairgrove** [stachenov/quazip#180]
Trying to build QuaZip on Linux Ubuntu 22.04 with Qt 6.5. My CMake version is 3.26.3.

I extracted the QuaZip sources to a directory such as this:
```
/home/myuser/../quazip/
```
Then I tried to run `cmake` like this:
```
cd /home/myuser/../quazip/
mkdir build
cd build
cmake -S .. -B . -D QUAZIP_QT_MAJOR_VERSION=6
```
This was the result:
```
CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:1 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.


CMake Error at CMakeLists.txt:1 (project):
  VERSION not allowed unless CMP0048 is set to NEW


-- Configuring incomplete, errors occurred!
```
It isn't finding QuaZip's VERSION, apparently.

Some time ago, with QuaZip 1.3 and Qt 5, I was able to complete the build successfully by using the code in the `ver` branch. What do I need to do now?

**Comment by cen1** [comment]
Both warnings make no sense to me as they do not correlate to the actual CMakeLists.txt as far as I can tell.

Which branch are you trying to build?

Tried to reproduce this on Debian 12, cmake 3.25.1, quazip master, no issues.

**Comment by bobhairgrove** [comment]
OK, I had two problems here ...
1. I forgot to extract the entire project and only had extracted the source directory;
2. I ran into a Qt6 bug concerning CMake.

The following command line built successfully now:
```
cmake -S .. -B . -DQUAZIP_QT_MAJOR_VERSION=6 -DCMAKE_PREFIX_PATH=/home/bob/code/Qt/6.5.3/gcc_64/lib/cmake/Qt6
```
Sorry for the noise ... however, it might be a good idea to add a note to the documentation that this is necessary for building with Qt 6?

**Comment by cen1** [comment]
You seem to have Qt located in a specific directory so that makes sense. I installed it from package manager and did not have to add anything extra for example.

**Comment by cen1** [comment]
Instructions to specify custom Qt install has been added to main readme.
