### ISSUE TITLE
error LNK2019

### ISSUE THREAD

**Issue by Alvazz** [stachenov/quazip#183]
>mainwindow.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static bool __cdecl JlCompress::compressDir(class QString,class QString,bool)" (__imp_?compressDir@JlCompress@@SA_NVQString@@0_N@Z) referenced in function "private: void __cdecl MainWindow::OnPackPlugin(void)" (?OnPackPlugin@MainWindow@@AEAAXXZ)

**Comment by Alvazz** [comment]
static link

**Comment by cen1** [comment]
The error indicates that quazip is not being linked into your project. Without knowing your setup (Cmake? Visual studio?) it's hard to give any further advice. Reopen if the issue is still relavant.
