### ISSUE TITLE
Compilation error, windows 10, QT 5.11

### ISSUE THREAD

**Issue by AsteriaGamer** [stachenov/quazip#21]
I can not compile the library. Used this article https://www.antonioborondo.com/zipping-and-unzipping-files-with-qt/. Zlib compiles normally, and at the stage of the assembly, Quazip gets the following error.

`./.obj\testquazipfileinfo.o:testquazipfileinfo.cpp:(.text+0xd2d): undefined reference to `_imp___ZNK16QuaZipFileInfo6412getNTFSmTimeEPi'
./.obj\testquazipfileinfo.o:testquazipfileinfo.cpp:(.text+0x10ce): undefined reference to `_imp___ZN10QuaZipFileD1Ev'
./.obj\testquazipfileinfo.o:testquazipfileinfo.cpp:(.text+0x10d7): undefined reference to `_imp___ZN6QuaZipD1Ev'
./.obj\testquazipfileinfo.o:testquazipfileinfo.cpp:(.text+0x16a8): undefined reference to `_imp___ZNK16QuaZipFileInfo6412getNTFSaTimeEPi'
./.obj\testquazipfileinfo.o:testquazipfileinfo.cpp:(.text+0x171f): undefined reference to `_imp___ZNK16QuaZipFileInfo6412getNTFScTimeEPi'
./.obj\testquazipfileinfo.o:testquazipfileinfo.cpp:(.text+0x1a35): undefined reference to `_imp___ZN10QuaZipFileD1Ev'
./.obj\testquazipfileinfo.o:testquazipfileinfo.cpp:(.text+0x1a3e): undefined reference to `_imp___ZN6QuaZipD1Ev'
collect2.exe: error: ld returned 1 exit status
Makefile.Release:118: recipe for target 'release\qztest.exe' failed
mingw32-make[2]: *** [release\qztest.exe] Error 1
mingw32-make[2]: Leaving directory 'E:/Qt/quazip-0.7.6/qztest'
Makefile:36: recipe for target 'release' failed
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory 'E:/Qt/quazip-0.7.6/qztest'
Makefile:66: recipe for target 'sub-qztest-make_first' failed
mingw32-make: *** [sub-qztest-make_first] Error 2`

**Comment by stachenov** [comment]
Follow Qmake reference to set up library paths. Or ignore these messages altogether, because the library itself compiled fine, only tests didn't.
