### ISSUE TITLE
Pulling this as sunmodule into my build.

### ISSUE THREAD

**Issue by dlautz314** [stachenov/quazip#25]
So no issues with library, just have a question about pulling this in to my build tree as a submodule & subproject of my main QT project. It seems for mac/linux the zlib dependency isn't specified (!win32: LIBS += -lz) when building the dynamic library, so I really cannot build it independently without making a change (forking I guess).

Is there an alternative approach to handle this use case? As I see no other comments on this point, I suspect there might be....or everyone just forks your repo :) 

Otherwise, I will probably do the same.

Thanks,
David

**Comment by stachenov** [comment]
It really depends on your build environment. If building from command line with `qmake`, running `qmake LIBS+=-lz` is enough. If building from Qt Creator, specifying `LIBS+=-lz` in the project settings will do. It is really machine-specific, that's why it isn't in the `.pro` file.

**Comment by dlautz314** [comment]
Ok, I just saw your comments per https://github.com/stachenov/quazip/issues/23 right after I posted, of course. 

I was just hoping for an approach to treat submodule more independently (didn't require changes to top-level parent project or build), but it is workable.

**Comment by RichardTea** [comment]
I use the following quazip_static.pri for Windows, Mac and Linux:
_Requires Qt5 on Windows due to header fun and games for static builds, though this might no longer be necessary._
```
DEFINES *= QUAZIP_STATIC

include($$PWD/../quazip.pri)

win32 {
    # On Windows zlib.h is not an SDK header
    # Redirect to the Qt5 one
    greaterThan(QT_MAJOR_VERSION, 4) {
        INCLUDEPATH *= $$PWD
        HEADERS += $$PWD/zlib.h
    } else {
        # There isn't a neat workaround in older versions of Qt
        error(quazip_static.pri requires Qt5 or later)
    }
}

unix {
    # Unix (Linux, Mac, BSD) have a system zlib library
    LIBS += -lz
}
```
Obviously update the include() path to find `quazip/quazip.pri` as needed.

The zlib.h referred to contains the following:
```
// Workaround for zlib.h on Windows
// Requires Qt5

#ifdef WIN32
#include <QtZlib/zlib.h>
#endif
```
I'm not sure if that's actually still needed for static builds, as I first did this around QuaZip 0.7.1
