### ISSUE TITLE
Quick question about use of QuaZIODevice.

### ISSUE THREAD

**Issue by dlautz314** [stachenov/quazip#27]
Library is working great between two QT applications, I am using QuaZIODevice to compress/decompress a memory buffer, which gets sent over the network.

My question is when using QuaZIODevice to compress a memory buffer, should there be any issues decompressing this buffer with another zlib library on IOS? Just confirming, as I need to interoperate with a non-QT application running on IOS. 

The IOS developer is having issues,  and I want to make sure I haven't chosen a solution that is QT specific.

Thanks.

**Comment by stachenov** [comment]
`QuaZIODevice` uses raw zlib calls, no Qt-specific stuff, except the implemented interface, of course. We use it to implement a custom application protocol in our company, which interoperates with a lot of other software, some written in Java using jzlib, some written in C# using SharpZipLib, no issues at all.

**Comment by dlautz314** [comment]
ok, thanks for the quick response, I assumed as much but wanted to confirm. 

I actually got it working with IOS developer, he is using https://github.com/1024jp/GzipSwift, and was getting an unknown error in a guard inflateEnd(..). Curiously, he removed the check, and the buffer was  decompressed correctly. 

I'd like to understand why he is getting the error though, as it seems a hack to remove the guard. Any thoughts?

**Comment by stachenov** [comment]
An unknown error sounds rather vague. Doesn't the library provide any kind of error code?

**Comment by dlautz314** [comment]
Sorry, I edited previous:

UPDATE: I guess his library is calling "status = inflate(&stream, Z_SYNC_FLUSH)", where he is expecting Z_STREAM_END(1).

Waiting for him to respond with specific error.

**Comment by dlautz314** [comment]
Ok, well I got tired waiting for a response from IOS developer, so I created a small method using zlib directly, to decompress the byte array returned from the QuaZIODevice compression.

My method seemed to successfully process the compressed input buffer calling inflate(), which eventually returned an error Z_BUF_ERROR. I fully realize this is not really an error, and just indicates no progress can be made (either no more input avail, or output space avail). I believe he is probably getting this error, expecting Z_STREAM_END instead.

In my method, the zlib inflate call seems to successfully process the entire input buffer.  But by returning Z_BUF_ERROR instead of Z_STREAM_END, does that indicate the original deflate stream (generated by QuaZIODevice) was not finished properly? Is there something I need additional I need to do? Or is this the way QuaZIODevice behaves when creating compressed output (aka deflate stream)?

NOTE: After examining the decompressed data, it seems it was entirely successful, albeit the Z_BUF_ERROR when input was exhausted.

I just want to understand if Z_BUF_ERROR is an acceptable result in this case after all input is processed (or should I be seeing a Z_STREAM_END? If so, I can instruct the IOS developer to adjust his assumptions.

Thanks.

**Comment by dlautz314** [comment]
Just followup, my code that uses QuaZIODevice to compress a buffer ("backupData", in snippet below). This works great between two QT applications right now (compress & decompress, no issues using QuaZIODevice), the only thing I am investigating here is how applications using native zlib should behave.

// Compress backup data to zip buffer IO device;
QBuffer zipBuffer;
zipBuffer.open(QIODevice::WriteOnly);
QuaZIODevice dev(&zipBuffer);
dev.open(QIODevice::WriteOnly);
dev.write(backupData.data(),backupData.size());
dev.flush();
dev.close();
zipBuffer.close();

As I said before, the native zlib doesn't seem to detect Z_STREAM_END when inflating the compressed buffer (zipBuffer.data()), although I do get a Z_BUF_ERROR instead, and confirm that buffer is indeed processed correctly.

I am calling flush on the QuaZIODevice, so I assume it is flushing the data to the QBuffer, and finishing the deflate stream? Or is there something I am missing?

Thanks again.

**Comment by stachenov** [comment]
Yes, I think you're right. `QuaZIODevice` should definitely use Z_FINISH when `close()` is called. Instead, it simply calls `flush()` if open in the write mode. Should be a simple fix. I'll get to it shortly.

**Comment by dlautz314** [comment]
Ok, great, thanks.

I actually modified flush() to except a flushType (default to Z_FLUSH_SYNC), and then passed Z_FINISH, in the call from close().

Curiously, with those changes, I am still having issues on the zlib inflate() logic, where it doesn't ever get a Z_STREAM_END (like it's not detecting the end of the deflate stream) when processing the compressed input buffer from  QuaZIODevice (it seems to only get Z_BUF_ERROR). When you get to it, let me know if you have any thoughts.

Thanks

**Comment by stachenov** [comment]
Sounds like the right thing to do except that I'll do it by overloading, not adding a parameter with a default value (for ABI compatibility), but that's not relevant here. I'll look into it.

**Comment by dlautz314** [comment]
Yep I agree, I was just trying to test a quick fix.

Thanks again.

**Comment by stachenov** [comment]
Finally got to it. The trick was that `deflate()` returned Z_STREAM_END when flushing the end-of-stream. My code was only expecting Z_OK.

**Comment by dlautz314** [comment]
Great, thanks Sergei. I'll pull it and give a whirl.

**Comment by themolecule** [comment]
Doing it this way, how does one add file name entries to the stream?

I'm wanting to download a database as a zip file, using database IDs as file names.

I would need to add data to a stream, and then send that over a socket.  I have it working well for individual files/entries (not zipped), but having trouble initializing objects to create a stream.

Any help or sample code?

**Comment by stachenov** [comment]
1. Your question doesn't have anything to do with this issue. Please don't hijack issues to ask unrelated suggestions.

2. Your question doesn't have anything to do with QuaZIODevice. Read this issue and zlib docs to understand why.

3. You'll have to use QuaZip/QuaZipFile. You may need some tweaking (such as enabling data descriptor) to get it to work over a socket, but it's possible. If you run into problems, then please read the docs, do your research and then open a new issue if you still have questions.
