### ISSUE TITLE
0.7.4 tarball is not backward-compatible

### ISSUE THREAD

**Issue by zgyarmati** [stachenov/quazip#3]
The new release tarball 0.7.4 under the versioned directory 'quazip-0.7.4' has a 'quazip' subdir, while the old, SF tarballs didn't have, just directly the source tree under the versioned dir 'quazip-0.7.3'.
 This breaks packaging/building setups in downstream projects (on my side: Buildroot and MXE).

**Comment by stachenov** [comment]
It's a migration artifact. I moved all the sources up the tree after that release, so the next one will not have this problem. I'll release 0.7.5 soon.

**Comment by zgyarmati** [comment]
Works well with the new rls, thx!
