### ISSUE TITLE
Reading file out of zip does not produce the file's contents on disk (buffered?)

### ISSUE THREAD

**Issue by richardson-trevor** [stachenov/quazip#30]
First off, excellent library. Saving us tons of time. The question I have is in regard to a read after write situation. We are modifying a file inside a zip using the following:
```
QuaZip zip(study.filepath);
if (zip.open(QuaZip::Mode::mdAdd)) {
    QuaZipFile zipFile(&zip);
    if (zipFile.open(QIODevice::WriteOnly, QuaZipNewInfo("study_info"))) {
        QJsonObject studyJson = study.writeToJSON();
        QJsonDocument jsonDoc(studyJson);
        zipFile.write(jsonDoc.toJson());
        zipFile.close();
    } else {
        qDebug() << "Failed to update study details. Could not open study_info file.";
    }
    zip.close();
} else {
    qDebug() << "Failed to update study details. Could not open zip at: " << study.filepath;
}
```
If I then read that same file using:
```
QJsonDocument BodyvizFileUtilities::studyInfoFrom(QFileInfo bvfFile) {
    QuaZipFile zipFile(bvfFile.absoluteFilePath(), "study_info");
    if (zipFile.open(QIODevice::ReadOnly)) {
        QJsonDocument jsonDoc(QJsonDocument::fromJson(zipFile.readAll()));
        zipFile.close();
        return jsonDoc;
    }
    qDebug() << "Failed to load study details. Could not open study_info file.";
    return QJsonDocument();
}
```
The updated contents are not present. The contents are those of the data **before** updating the zip. Now, I could understand this if the zip wasn't getting updated properly on disk, but if I crack open the zip and look at the contents, the update operation is indeed working. 

It's behaving as if it reading from buffered or cached data, but I can't quite figure out where that would be if that's the case. Greatly appreciate your time and any input!

**Comment by stachenov** [comment]
I'm afraid it's worse than it looks. I haven't used `mdAdd` myself, but judging from what I know about minizip (the backend), it probably dosn't support updating _files_ in the archive. You can update an archive by adding files into it, but when you try to “overwrite” an existing file, you end up just adding another file with the same name. Now your archive contains _two_ files with the same name. `QuaZipFile` probably opens the first one, whatever external utility you used to “crack it open” probably opens the last one.

I have to confirm it yet, but if it's the case, the only way to update the whole archive I can think of is to extract it somewhere and then re-pack. Not only it's a needless hassle, but it will probably corrupt a lot of metadata too (timestamps, format versions, comments...). But I can't think of a better way.

**Comment by richardson-trevor** [comment]
That makes a lot of sense with what we're seeing. In our case I think we should be okay re-packing the whole thing, as the timestamps, etc. aren't important as of right now. Appreciate the input!

**Comment by CrawlWu** [comment]
QuaZip::open(QuaZip::mdAdd) update file will causes multiple copies. _Make a summary so that users of the library can find this probem._
