### ISSUE TITLE
./qztest: symbol lookup error: ./qztest: undefined symbol: _ZN6QuaZip14setUtf8EnabledEb

### ISSUE THREAD

**Issue by dgrr** [stachenov/quazip#34]
Hello,

I was trying to implement quazip in my project but it fails when creating the QuaZip object.
Also I after compiling I got the title error.

Thanks.

**Comment by stachenov** [comment]
What do you mean by implementing it in your project? How are you using it?

**Comment by dgrr** [comment]
Just instancing the object breaks the program
```c
qDebug() << "zip";
QuaZip zip;
qDebug() << "unzip";
```
The `unzip` is not printed. But I can compile the project.
And executing the qztest after compiling gives me the error in the title.

**Comment by stachenov** [comment]
How did you compile and link QuaZIP? What is qztest? Is it QuaZIP test suite or your project that has the same name by coincidence? What is your environment? How do you link your project? Really, you don't think it's possible to just magically solve your problem without any details?

The only idea I can think of right away is that you link to a different version than you compile with. Perhaps there's an older version of QuaZIP somewhere.
