### ISSUE TITLE
how to decompress zip file in a zip archive

### ISSUE THREAD

**Issue by zhuhuazha** [stachenov/quazip#36]
i have a zip archive, which is a lot zip file in . How can decompress these zip file?

**Comment by stachenov** [comment]
Upack them into a temporary directory then work with them just like you'd do with regular archives. I'm afraid it's not possible to use a QuaZip-QuaZipFile-QuaZip chain to do everything in-RAM because QuaZipFile is sequential and QuaZip can't read from sequential devices.

**Comment by zhuhuazha** [comment]
i have done it in memory. The solution is: 
1、use quazip to access the zip archive, and get the QuaZipFile object which is an zip file in the archive; 
2、read the QuaZipFile to a QByteArray, and then generate a QBuffer object which is subclass of QIODevice; 
3、construct a QuaZip using QBuffer object,  like this:
       QuaZip inZipArchive( &buffer );
      this is the first keypoint.
4、open the QuaZip, and traverse the file in the zip file, and get  the inside QuaZipFile, like this:
      for( bool f1 = inZipArchive.goToFirstFile(); f1; f1 = inZipArchive.goToNextFile() )
      {
                QString inZipFilePath = inZipArchive.getCurrentFileName();
                QuaZipFile inZipFile;
                 //keypoint 2
                 inZipFile.setZip( &inZipArchive );
                 inZipFile.setFileName( inZipFilePath );
      }
      Here, we need QuaZipFile.seteZip, not use QuaZipFile( inZipArchive.getZipName() , inZipFilePath ).
      because  inZipArchive.getZipName() will be null.

**Comment by stachenov** [comment]
By in-RAM I mean't on the fly, without reading the whole file into RAM. Otherwise it is, of course, possible, but will work only for files of reasonable size assuming you have enough RAM.

**Comment by zhuhuazha** [comment]
yes, thank you all the same.
