### ISSUE TITLE
Consider creating a portfile for vcpkg

### ISSUE THREAD

**Issue by hubbergit** [stachenov/quazip#42]
vcpkg (https://github.com/microsoft/vcpkg) is another C++ library/package manager that is quite popular at the moment.

Please consider creating a portfile for QuaZIP in vcpkg repository. A port file is more or less just a cmake script. Unfortunately I have only limited knowledge of cmake, therefore I am not able to contribute that port file by myself at the moment (maybe next year).

Making QuaZIP accessible via vcpkg would make it accessible to a lot of people.

**Comment by stachenov** [comment]
I have NO knowledge of CMake. All things CMake were contributed by various people. So no luck unless someone else issues a PR or I make some free time to finally learn CMake, which is unlikely because I don't really need it.

**Comment by hubbergit** [comment]
There is a port for QuaZIP available in vcpkg since some time now. Therefore this issue is obsolete now.
