### ISSUE TITLE
Quazip doesn't get file modification date/time

### ISSUE THREAD

**Issue by jamesbloomscheff** [stachenov/quazip#43]
In getCurrentFileInfo, at this place in the code
 info->dateTime=QDateTime(
      QDate(info_z.tmu_date.tm_year, info_z.tmu_date.tm_mon+1, info_z.tmu_date.tm_mday),
      QTime(info_z.tmu_date.tm_hour, info_z.tmu_date.tm_min, info_z.tmu_date.tm_sec));
 
the information in info_z.tmu_date is completely bogus. Most of the data is 0, the year is 1980, and the month is 4294967295. I can see in 7-Zip that the correct information should be 2018-02-23 16:37

I don't see version information for quazip, but the copyright is 2005-2014.
unzip.c has version 1.1

**Comment by jamesbloomscheff** [comment]
Some of the information I posted is probably incorrect. It turns out that the debug version of my program was linking to the release version of quazip. I have fixed that. After fixing it, I can no longer step into getCurrentFileInfo to see what it is doing. The date/time returned from getCurrentFileInfo is still invalid.

**Comment by stachenov** [comment]
You can see version information in NEWS.txt or in Doxyfile (`PROJECT_NUMBER`). And I suggest update first then check whether the problem is still there.

**Comment by jamesbloomscheff** [comment]
The version of quazip was slightly out of date, I've corrected that. I'm now running the latest version.
The version of zlib was even more out of date. I've corrected that. I'm now running the latest version.
I'm still seeing the same problem with the same values that I described in my original post.

**Comment by stachenov** [comment]
Well, I need an example of an archive to test it. I can't fix a problem I can't reproduce.

Alternatively, you could try getting NTFS date/times. Perhaps your archive contains only NTFS date/times, and that's what 7-zip displays (check the precision—if at least one time has odd seconds, it's definitely an NTFS one because the regular times are stored with ridiculous 2-second presision).

**Comment by jamesbloomscheff** [comment]
[cant_get_dates.zip](https://github.com/stachenov/quazip/files/3596817/cant_get_dates.zip)

I can easily believe that the archive may only contain NTFS date/times. The tool that makes it is homegrown and has been replaced several times. I have no way of knowing which iteration made the file. With that said, I can't seem to get any of the NTFS date/times. They all return invalid date/times.

**Comment by jamesbloomscheff** [comment]
It appears that quazip is looking for the extended time stamp info with a type == 0x000a while the archive has the extended time stamp info with the type == 0x5455

**Comment by stachenov** [comment]
Type 0x000a is the NTFS time stamp documented in APPNOTE.txt. Type 0x5455 is only mentioned as a common third-party extension, but is not described. QuaZIP obviously doesn't support this extension... yet. It would be easier to add this support if this timestamp format was documented somewhere. Any ideas where to look except Google?

**Comment by jamesbloomscheff** [comment]
I found some info here: https://issues.apache.org/jira/browse/COMPRESS-210

Using that information, I was able to process the time almost correct. 7-zip reports the modification time to the minute, not the second, and differes by about 5 minutes from what I get from the extra.

**Comment by stachenov** [comment]
5 minute difference is really weird... OK, I have everything I need, and I'll look into it.

**Comment by jamesbloomscheff** [comment]
The time difference between my calculation and 7-zip turned out to be my issue. I had a sign extension problem with the conversion from QByteArray.

Thanks for your help

**Comment by stachenov** [comment]
All right, so you can for now just get this time from the extension attribute, and I'll add support for this time format in a future version.

**Comment by stachenov** [comment]
Oh goodness. I started implementing it and suddenly found out that minizip backend returns the central dir version of the extra field. The problem is, with this extended time they decided to only place modification time into the central dir. So there is no way to get access time or creation time unless I find some way to get minizip return the local file header version instead.

**Comment by stachenov** [comment]
Found a way to get the local header variant of the extra field. A bit inconvenient as it requires to open the file. But better than nothing. It's in the master now. Now you can get the modification time directly from `QuaZipFileInfo64` and access/creation times from an open `QuaZipFile`. Feel free to reopen or comment if something is amiss.
