### ISSUE TITLE
static linking exception question

### ISSUE THREAD

**Issue by tonka3000** [stachenov/quazip#5]
Hey,

thanks for QuaZip. I have a question about the static linking exception. With it you allow to static linking quazip f.e. i have a exe called `mytool.exe` (i assume windows) and it is dynamically linked to `Qt5Core.dll`, and now it is allowed to link QuaZip statically to `mytool.exe`. Is it also allowed to link statically to a shared library like `mylib.dll`? If it's allowed, please can you add some term like shared libraray also to the exception, because it would clarify the situation (also the "it's not allowed to link statically to shared libs" if that's your wish).

Thanks in advance  
Tonka

```
STATIC LINKING EXCEPTION

The copyright holders give you permission to link this library with
independent modules to produce an executable, regardless of the license
terms of these independent modules, and to copy and distribute the
resulting executable under terms of your choice, provided that you also
meet, for each linked independent module, the terms and conditions of
the license of that module. An independent module is a module which is
not derived from or based on this library. If you modify this library,
you must extend this exception to your version of the library.
```

**Comment by stachenov** [comment]
I don't see anything wrong with the current wording. It explicitly allows you to link QuaZIP with any other modules in any way. It doesn't even say “statically” anywhere except the exception title. You may link QuaZIP to anything, statically or dynamically, regardless of what terms that “anything” is licensed under. The resulting executable can then be distributed under any license whatsoever.

All that, of course, assumes that other modules' licenses allow you to do it too.
