### ISSUE TITLE
Instructions update

### ISSUE THREAD

**Issue by shnaps** [stachenov/quazip#57]
Hi! I'm having problems building quazip on windows 10. Can you update the instructions for it?

**Comment by shnaps** [comment]
Also connected to this [link](https://github.com/petrovvlad/freeLib/issues/23)

**Comment by stachenov** [comment]
There is nothing Windows 10-specific. Nor with QuaZIP or with the linked issue. What you need is the instructions for whatever build system you're using (probably Creator/qmake), how to tell it where your files are. RTFM. QuaZIP has nothing to do with it. Compile it like you'd compile any library using Qt and zlib.

**Comment by shnaps** [comment]
Still, something wrong with my build.
Here is updated part of my config 
![image](https://user-images.githubusercontent.com/18357973/75315329-56161000-5817-11ea-9b92-ee3f72ae48db.png)

I can open every and go inside of zlib.h 
![image](https://user-images.githubusercontent.com/18357973/75315153-c40e0780-5816-11ea-837d-d2dd850a5bd6.png)

And here is my zlib.h file(fresh, just compiled) in the same path that I'm using in config
![image](https://user-images.githubusercontent.com/18357973/75315219-fd467780-5816-11ea-9bd4-3060ec2bcc3b.png)

What is wrong?
