### ISSUE TITLE
Provide SHA512 and SHA256 checksums

### ISSUE THREAD

**Issue by einsteinsfool** [stachenov/quazip#6]
## Description
Provide SHA512 and SHA256 checksums for all files both on GitHub in the releases section and SourceForge in files section. All in plaintext so users don't need to download the checksum which would defeat the whole purpose of them.

PS Both [MD5](https://en.wikipedia.org/wiki/MD5#Security) and [SHA1](https://en.wikipedia.org/wiki/SHA-1#SHAttered_%E2%80%93_first_public_collision) are breaked and shouldn't be provided because they give a false sense of security.

## Expected Behavior
After downloading the file I should be able to verify if the file I have is the same as the one uploaded by the maintainers.

## Current Behavior
Users can't verify the downloaded files.

## Steps to Reproduce
1. Download an installer.
2. An attacker intercepts the file and swaps it with a modified malicious one.
3. Don't verify the file because there are no checksums.
4. Get ~~f...~~ hacked. (couldn't resist)

**Comment by stachenov** [comment]
In plaintext, but where exactly? I don't get it, how on earth can I provide checksums without user having to download it?

**Comment by einsteinsfool** [comment]
In the description of the release. I saw projects that do that both on GitHub and SourceForge (`readme.txt` file). Couldn't find them this time.

**Comment by stachenov** [comment]
I could, but what's the point? You assume that the attacker got GitHub or your PC hacked. How else one would intercept a file that is downloaded through the man-in-the-middle-attack-proof HTTPS?

Adding pages to the Internet Archive sounds like a good idea, though. And then it certainly makes sense to provide checksums on the page itself. I'll get to it soon. Not for SF, as I no longer use it, but just for GitHub.

**Comment by einsteinsfool** [comment]
Well, I meaned that when making a new release, you'd generate checksums for each file and pasted them in the description on GitHub. Then you'd add that page to Internet Archive (IA) and if your GitHub account or GitHub itself gets hacked or phished users could check the checksums on IA.

But you're correct that without IA providing checksums on GitHub is useless. Didn't think it through.

**Comment by stachenov** [comment]
Done.
