### ISSUE TITLE
Feature request: add an option to disable shared/static library

### ISSUE THREAD

**Issue by lgbaldoni** [stachenov/quazip#70]
I'd do it myself, but I'm unsure about the desired logic.

**Comment by stachenov** [comment]
I'm assuming this is yet another CMake request? Because with qmake you decide that manually. Will have to deal with #60 first then. Maybe update CMake version required.

**Comment by a17r** [comment]
Yes please, I am currently having to manually patch out the static lib.

**Comment by lgbaldoni** [comment]
@stachenov why? Is qt4 still a thing?

**Comment by stachenov** [comment]
How is this related to Qt4? It isn't even mentioned anywhere in this thread.

**Comment by stachenov** [comment]
I've created #82 for CMake-related discussion. It's now spread among several issues/PRs, some of which are closed, and that makes hard to keep track of all those and search for them. Please don't post here any more.

**Comment by lgbaldoni** [comment]
> How is this related to Qt4? It isn't even mentioned anywhere in this thread.

You mentioned https://github.com/stachenov/quazip/pull/60 and I wondered about it, perhaps in the wrong place.
