### ISSUE TITLE
Cmake build does not specify project version

### ISSUE THREAD

**Issue by p01arst0rm** [stachenov/quazip#71]
there is no project version definition defined in the
root CMakeLists.txt file. This can cause issues
when other buildsystems try to check the current 
installed version of quazip.

**Comment by p01arst0rm** [comment]
this issue was actually fixed in commit 
5c1f52997b01bd800afe980a9e22c188787062cb
with the additions of lines 9 & 10

set(QUAZIP_LIB_VERSION 1.0.0)
set(QUAZIP_LIB_SOVERSION 1)

it looks like on 0.9 the `version:` in quazip.pc is
left blank. I guess this problem is alredy fixed.
Could you possibly provide a 0.9.1 build or
something of the sort?

**Comment by stachenov** [comment]
I can't. That commit merged a lot of 1.0-related stuff, not just version. I don't understand CMake, so I can't just randomly add some lines hoping that it fixes whatever you think it should fix.

I can create a branch for 0.9.x, though, and then you can issue a PR containing whatever changes you want to see in 0.9.1. Then I'd just merge it and release a new version.

**Comment by p01arst0rm** [comment]
sounds like a good idea :)

**Comment by stachenov** [comment]
Done. The branch is v0.9.x. Don't forget to switch to it when creating a PR.

Since you're using CMake, you may wish to take a look at #60. There's a lot of CMake-related changes being discussed there.

**Comment by p01arst0rm** [comment]
its worth noting that a lot of package managers default to using cmake over qmake.... at least Pacman on arch does.

**Comment by stachenov** [comment]
I'm planning to learn CMake as soon as possible. I've also heard a rumor that Qt itself may switch to CMake in the future.

Meanwhile, 0.9.1 is out. Enjoy!
