### ISSUE TITLE
QuaZipFile's destructor in the stack will crash.

### ISSUE THREAD

**Issue by CrawlWu** [stachenov/quazip#90]
Simple TEST CASE(debug mode use release dll):

    int main(int argc, char *argv[])
    {
        QApplication a(argc, argv);
        {
            QuaZipFile analysisFile("D:/PROGRAMMING/SightPro/fileMgr/fmTest/TestData/2020-07-21_1C19-probe.expzip", "run.exp");
        }
        return a.exec();
    }

**Comment by stachenov** [comment]
It doesn't crash for me. Please be more specific.

**Comment by CrawlWu** [comment]
When debug configuration use the release dll.

**Comment by cen1** [comment]
It is generally best practice to link against debug libraries when doing a debug build. Linking to release can get you iterator_debug_level mismatch problems and weird stuff happening.

**Comment by stachenov** [comment]
Closing this due to lack of any details whatsoever. Works-for-me.

**Comment by CrawlWu** [comment]
My os is Windows,several qt versions from 5.12 have the problems.
