### ISSUE TITLE
Test executable not being buitl on 1.x

### ISSUE THREAD

**Issue by lgbaldoni** [stachenov/quazip#93]
Unless I'm doing something wrong, I have Qt5Test and Qt5Network in addition to Qt5Core.

ctest fails with:
```
Unable to find executable: /home/abuild/rpmbuild/BUILD/quazip-1.1/build/qztest/qztest
1/1 Test #1: qztest_test ......................***Not Run   0.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.00 sec

The following tests FAILED:
          1 - qztest_test (Not Run)
Errors while running CTest
```

**Comment by stachenov** [comment]
Tests are not built by default. The easiest way to run tests is to build the `check` target, which depends on `qztest`. It's [in the docs](https://stachenov.github.io/quazip/#test).

**Comment by lgbaldoni** [comment]
My bad, thanks.
