### ISSUE TITLE
Linking troubles when using --no-undefined

### ISSUE THREAD

**Issue by lgbaldoni** [stachenov/quazip#95]
As per subject, I'm seeing unresolved symbols when the linker is passed -Wl,--no-undefined.
Perhaps one needs to append -lz to Libs: in pkgconfig? Or maybe cmake has a cleverer way to do this?

**Comment by stachenov** [comment]
I'm not sure I follow. Perhaps pkgconfig needs `-lz`, but what CMake has to do with it? When building with CMake, pkgconfig is not needed at all, I believe. Simply
```
find_package(QuaZip-Qt5)
target_link_libraries(<target name> QuaZip::QuaZip)
```
It will bring the necessary dependencies along, including zlib and Qt.

Or are you referring to pkgconfig *generation* with CMake during build time? If so, then I don't think there's a better way than just appending `-lz`. I've added one now, could you check whether it fixes the problem?

**Comment by lgbaldoni** [comment]
Sorry, a major blunder on my part and in fact I can't reproduce it anymore.

Please disregard this and I think https://github.com/stachenov/quazip/commit/833b38005170e23393da26d96fe4aaeb82a39ce5 can be reversed.

**Comment by stachenov** [comment]
I don't see any meaning in reversing it... No harm in linking to zlib explicitly.
